package com.iLab.assessment.CommonMethods;
import com.iLab.assessment.PageObject.Apply_Page;
import com.iLab.assessment.PageObject.Careers_Page;
import com.iLab.assessment.PageObject.Home_Page;
import com.iLab.assessment.PageObject.Jobs_Page;
import org.openqa.selenium.support.PageFactory;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.Assert;;
import java.util.concurrent.TimeUnit;

public class Action_Functions extends driverSetup {

    public Home_Page homePage;
    public Careers_Page careersPage;
    public Jobs_Page jobsPage;
    public Apply_Page applyPage;
    static WebDriverWait wait;

    public Action_Functions() {

        driver = setupWebDriver("chrome");

        careersPage = PageFactory.initElements(driver, Careers_Page.class);
        homePage = PageFactory.initElements(driver, Home_Page.class);
        jobsPage = PageFactory.initElements(driver, Jobs_Page.class);
        applyPage = PageFactory.initElements(driver, Apply_Page.class);
        wait = new WebDriverWait(driver,60);
    }

    public void driverInitializer(String website) {

        driver.get(website);
        driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
        driver.manage().window().maximize();
    }

    public void closeDriver() {

        driver.close();
    }

    public static void nav_to_careers(){

        scrollToElement(Home_Page.careerLink);
        Home_Page.careerLink.click();
    }

    public static void select_country( String country){

        if(country.equalsIgnoreCase("North America")){

            scrollToElement(Careers_Page.northAmerica);
            Careers_Page.northAmerica.click();

        }else if(country.equalsIgnoreCase("South Africa")){

            scrollToElement(Careers_Page.southAfica);
            Careers_Page.southAfica.click();

        }else if(country.equalsIgnoreCase("Australia")){

            scrollToElement(Careers_Page.australia);
            Careers_Page.australia.click();

        }else if (country.equalsIgnoreCase("United Kingdom")){

            scrollToElement(Careers_Page.united_Kingdom);
            Careers_Page.united_Kingdom.click();

        }else{

            scrollToElement(Careers_Page.brazil);
            Careers_Page.brazil.click();
        }
    }

    public static void select_job(){

        Jobs_Page.jobOpening.click();
    }

    public static void click_apply_online(){

        scrollToElement(Apply_Page.btnApplyOnline);
        try {
            Thread.sleep(2500);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        Apply_Page.btnApplyOnline.click();
    }

    public static void enter_name(String name){

        scrollToElement(Apply_Page.txtPhoneNumber);
        Apply_Page.txtName.sendKeys(name);
    }

    public static void enter_email(String email){

        Apply_Page.txtEmail.sendKeys(email);
    }

    public static void enter_autogenerated_number(){

        Apply_Page.txtPhoneNumber.sendKeys(generatePhone());

        try {
            Thread.sleep(3000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }

    public static void click_submit_application(){

        scrollToElement(Apply_Page.btnSubmit);
        Apply_Page.btnSubmit.click();
    }

    public static void assert_error_message(){

        try {
            Thread.sleep(3000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }

        Assert.assertEquals("There are errors in your form.",Apply_Page.errorMessage.getText());
    }

}
