package com.iLab.assessment.StepDefs;
import com.iLab.assessment.CommonMethods.Action_Functions;
import cucumber.api.java.en.Given;
import cucumber.api.java.en.Then;
import cucumber.api.java.en.When;


public class Job_Application_Stepdefs {

    Action_Functions myfunctions = new Action_Functions();

    @Given("^As a user I launch the iLabQuality web page$")
    public void as_a_user_I_launch_the_iLabQuality_web_page() {

        myfunctions.driverInitializer("https://www.ilabquality.com/");

    }

    @When("^I click Careers$")
    public void i_click_Careers() {

        Action_Functions.nav_to_careers();
    }

    @When("^I click South Africa$")
    public void i_click_South_Africa() {

        Action_Functions.select_country("South Africa");
    }

    @When("^I click first job opening$")
    public void i_click_first_job_opening() {

        Action_Functions.select_job();
    }

    @When("^I click Apply Online button$")
    public void i_click_Apply_Online_button() {

        Action_Functions.click_apply_online();
    }

    @When("^I capture Name \"([^\"]*)\"$")
    public void i_capture_Name(String name) {

        Action_Functions.enter_name(name);
    }

    @When("^I capture Email \"([^\"]*)\"$")
    public void i_capture_Email(String email) {

        Action_Functions.enter_email(email);
    }

    @When("^I capture Phone$")
    public void i_capture_Phone() {

        Action_Functions.enter_autogenerated_number();
    }

    @When("^I click Send Application button$")
    public void i_click_Send_Application_button() {

        Action_Functions.click_submit_application();
    }

    @Then("^I verify error message$")
    public void i_verify_error_message() {

        Action_Functions.assert_error_message();

        try {
            Thread.sleep(3000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }

        myfunctions.closeDriver();
    }
}
